@startuml
object Mechanic
object Intervention
object Client
object Vehicle
object RepairingPack

Mechanic *-- "*" Intervention
Mechanic ..> Vehicle
Mechanic ..> RepairingPack
Mechanic ..> Client
Client "1" *-down- Vehicle
RepairingPack "0..1" o-- "*" Intervention
Intervention o-- "0..1" Vehicle
@enduml
