@startuml
object Mechanic
object Intervention
object Client
object Vehicle
object RepairingPack

Mechanic ..> Intervention : create
Mechanic ..> RepairingPack : create
Mechanic ..> Vehicle : see
Mechanic ..> Client : see
Client "1" --o Vehicle
RepairingPack "1" --o Intervention
Intervention o-- "1" Vehicle
@enduml
