@startuml
!include configuration/StateDiagramsSetUp.puml

state 7 as "OPENED_DASHBOARD"
state startState as "INITIAL"

startState --> signin
note on link
    <b>User requests to</b>
    * signin
end note

state signin {
state 2 as " "
state 3 as " "
state 9 as " "
state 4 <<choice>>

[*] -down-> 2

2 -down-> 3
note on link
<b>System requires</b>
* username
* password
* repeat password
<b>System allows</b>
* cancel
end note

3 -[#red]-> [*]
note on link
<b>User requests to
* cancel
end note

3 -down-> 4
note on link
<b>User provides</b>
* username
* password x2
end note

4 -down-> [*]

4 -[#red]-> 9
note on link
[username exists]
end note

9 -[#red]-> 2
note on link
    System shows error username already used
end note

}

signin --> openDashboard

openDashboard --> 7

@enduml
