@startuml
!include StateDiagramsSetUp.puml


[*] --> INITIAL

INITIAL --> OPENED_DASHBOARD
 note on link
     login
     sign in
 end note

OPENED_DASHBOARD --> OPENED_VEHICLES
    note on link
         openVehicles
    end note
OPENED_DASHBOARD --> OPENED_DASHBOARD
    note on link
         createIntervention
         finishIntervention
    end note

OPENED_VEHICLES --> OPENED_VEHICLES
    note on link
         createVehicle
         configVehicle
         deleteVehicle
         importVehicles
    end note

OPENED_VEHICLES --> OPENED_DASHBOARD
    note on link
     createIntervention
     openDashboard
    end note


OPENED_DASHBOARD --> OPENED_CLIENTS
    note on link
         openClients
    end note

OPENED_CLIENTS --> OPENED_CLIENTS
    note on link
     createClient
     configClient
     deleteClient
    end note

OPENED_CLIENTS --> OPENED_DASHBOARD
    note on link
     createIntervention
     openDashboard
    end note


OPENED_DASHBOARD --> OPENED_INTERVENTIONS
    note on link
         openInterventions
    end note
OPENED_INTERVENTIONS --> OPENED_INTERVENTIONS
    note on link
         billing intervention
         openIntervention
    end note
OPENED_INTERVENTIONS --> OPENED_DASHBOARD
    note on link
     createIntervention
     openDashboard
    end note

OPENED_DASHBOARD --> [*]
    note on link
    logout
    closeApp
    end note
OPENED_VEHICLES --> [*]
    note on link
    logout
    closeApp
    end note
OPENED_CLIENTS --> [*]
    note on link
    logout
    closeApp
    end note
OPENED_INTERVENTIONS --> [*]
    note on link
    logout
    closeApp
    end note
@enduml