@startuml
skinparam linetype polyline



package app {

    package resourses {
        package resourceX
    }

    package util {
        package converters
        package filters
    }

    package dtos

}

package webapp #e1eced {
    package views

    package components {
        package agrim {

        }
    }

    package css

    package templates

}

views ..> templates
views ..> agrim
views ..> css
views .down.> resourceX
views .down.> converters
agrim .down.> resourceX
views .down.> dtos
resourceX ..> dtos
resourceX ..> filters


@enduml
