@startuml
left to right direction

package InterventionsManagement {
:mechanic: --|> :user:
:developer: --|> :user:
:boss: --|> :user:

:user: --> (createIntervention)
:user: --> (finishIntervention)
:boss: --> (openInterventions)
:developer: ---> (openInterventions)
:boss: --> (billInterventions)
:user: --> (openMyInterventions)
:user: --> (pauseInterventions)
:user: --> (resumeInterventions)
(createIntervention) ..> (openDashboard) : <<include>>
(finishIntervention) ..> (openDashboard) : <<include>>
(billInterventions) ..> (openInterventions) : <<include>>
}
@enduml
