@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view VehiclesView
view ConfigVehicleView
controller ConfigVehicleController
model Vehicle
model VehiclesDao

user -right-> VehiclesView
note on link
    configClient(vehicleId, clientFullName)
end note

user -right-> ConfigVehicleView
note on link
    setVehicleInfo(info)
end note

VehiclesView -down-> ConfigVehicleView
note on link
   new configVehicle(vehicle, clientFullName)
end note

ConfigVehicleView -right-> ConfigVehicleController
note on link
    save(vehicle)
end note


ConfigVehicleController --> VehiclesDao
note on link
    save(vehicle)
end note

ConfigVehicleView --> Vehicle
ConfigVehicleController .. "1" Vehicle
VehiclesDao .. Vehicle
@enduml
