@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view VehiclesView
view CreateVehicleView
controller CreateVehicleController
controller OpenClientsController
collaboration ":Collaboration OpenVehicles" as OpenVehicles
model VehiclesDao
model ClientsDao
model Vehicle
model Client

user -right-> VehiclesView
note on link
    createVehicle()
end note

user --> CreateVehicleView
note on link
setVehicle(data)
searchClient(text)
setClient(clientId)
confirmCreation()
end note

VehiclesView -down-> CreateVehicleView
note on link
    new CreateVehicleView()
end note

CreateVehicleView -right-> CreateVehicleController
note on link
    createVehicle(vehicle)
end note

CreateVehicleView -right-> OpenClientsController
note on link
    searchClients(query)
end note

CreateVehicleView --> OpenVehicles
note on link
openVehicles()
end note

CreateVehicleView --> "1" Vehicle
CreateVehicleView --> "*" Client

CreateVehicleController -right-> VehiclesDao
note on link
    createVehicle(vehicle)
end note

OpenClientsController --> ClientsDao
note on link
    searchCliensByName(query)
end note

VehiclesDao .... Vehicle

ClientsDao .. Client

CreateVehicleController .right. "1" Vehicle

OpenClientsController .. "*" Client
@enduml