@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view ClientsView
view CreateClientView
controller CreateClientController
collaboration ":Collaboration OpenClients" as OpenClients
model ClientsDao
model Client

user -right-> ClientsView
note on link
    createClient()
end note

user --> CreateClientView
note on link
    setFullName(fullName)
    setBillableHours(billableHours)
    confirmCreation()
end note

ClientsView -down-> CreateClientView
note on link
    new CreateClientView()
end note

CreateClientView -right-> CreateClientController
note on link
    createClient(client)
end note

CreateClientView --> "1" Client

CreateClientView --> OpenClients
note on link
openClients()
end note

CreateClientController -right-> ClientsDao
note on link
    createClient(client)
end note

ClientsDao .. Client

CreateClientController .right. "1" Client
@enduml