@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor actor

view MenuView
view DashboardView

controller OpenDashboardController

model InterventionsDao
model VehiclesDao
model Intervention
model Session
model Vehicle

actor --> MenuView
note on link
    openDashboard()
end note

MenuView -right-> DashboardView
note on link
    new DashboardView()
end note

DashboardView -down-> Session
note on link
    getMechanic()
end note
DashboardView -down-> Intervention
DashboardView -down-> Vehicle

DashboardView -right-> OpenDashboardController
note on link
    searchActiveInterventions(mechanicId)
    searchVehicle(vehicleId)
end note

OpenDashboardController -down-> InterventionsDao
note on link
    searchActiveInterventions(mechanicId)
end note

OpenDashboardController -right-> VehiclesDao
note on link
    searchVehicle(interventionId)
end note

OpenDashboardController .. Vehicle
VehiclesDao .down.. Vehicle
OpenDashboardController .down. "0..*" Intervention
InterventionsDao -left- Intervention

@enduml