@startuml

!include configuration/StateDiagramsSetUp.puml

state initial as ":INITIAL"

state start1 as "OPENED_DASHBOARD"
state start2 as "OPENED_INTERVENTIONS"
state start3 as "OPENED_VEHICLES"
state start4 as "OPENED_CLIENTS"

start1 --> logout
    note on link
    <b>User request to</b>
    * logout
    end note
start2 --> logout
    note on link
    <b>User request to</b>
    * logout
    end note
start3 --> logout
    note on link
    <b>User request to</b>
    * logout
    end note
start4 --> logout
    note on link
    <b>User request to</b>
    * logout
    end note

state logout {
[*] --> [*]
}

logout --> initial
note on link
    <b>System allows</b>
    * login
    * sign in
end note

@enduml
