@startuml
	class CreateInterventionController {
	+createIntervention(intervention)
	}

	CreateInterventionController --> InterventionsDao
	CreateInterventionView --> CreateInterventionController
@enduml