@startuml
	class OpenClientsController {
	+readAllClients()
	+searchClients(query)
	}

	CreateVehicleView --> OpenClientsController
	OpenClientsController --> ClientsDao
	ClientsView --> OpenClientsController
@enduml