language: java
jdk:
  - openjdk11
branches:
  only:
    - master
    - develop
notifications:
  email:
    recipients:
      - ilya.kab@gmail.es
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS agrimManager;'
script:
  - mvn verify
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=ruskab-github -Dsonar.login=$SONAR