language: java
addons:
  chrome: stable
jdk:
  - openjdk11
branches:
  only:
    - develop
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
      - ilya.kab@gmail.es
services:
  - docker

script:
  - docker-compose -f docker-compose-travis.yml up -d
  - docker ps
  - mvn test -Denvironment=database
  # test unitario  de integracion con cobertura
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report -Dtest=api.business_controllers.*IT,api.api_controllers.*IT,api.DispatcherIT
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=ruskab-github -Dsonar.login=$SONAR

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU
  app: agrim-manager
  on:
    repo: Ruskab/agrimManager
    branch: develop