language: java
addons:
  chrome: stable
jdk:
  - openjdk11
branches:
  only:
    - develop
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
      - ilya.kab@gmail.es
services:
  - docker

script:
#  - docker-compose -f docker-compose-travis.yml up -d
#  - docker ps
#  - mvn clean test -Denvironment=database
  # all test with coverage
#  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent clean verify org.jacoco:jacoco-maven-plugin:report -Dtest=business_controllers.unittest.*Test,api_controllers.unittest.*Test,DispatcherIT,api.business_controllers.*IT,api.api_controllers.*IT
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent clean verify org.jacoco:jacoco-maven-plugin:report -DskipTests
#  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=ruskab-github -Dsonar.login=$SONAR

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: agrim-manager
  on:
    repo: Ruskab/agrimManager
    branch: develop
  edge: true