language: java
addons:
  chrome: stable

jdk:
  - openjdk11
branches:
  only:
    - master
    - develop
    - issue#36
notifications:
  email:
    recipients:
      - ilya.kab@gmail.es
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS agrimManager;'
  - sleep 4
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('admin') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sleep 4
  - sudo mysql_upgrade
  - sudo service mysql restart

script:
  - mvn verify
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=ruskab-github -Dsonar.login=$SONAR