language: java
addons:
  chrome: stable

jdk:
  - openjdk11
branches:
  only:
    - master
    - develop
    - issue#36
notifications:
  email:
    recipients:
      - ilya.kab@gmail.es
services:
  - mysql

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root


script:
  - mvn verify
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=ruskab-github -Dsonar.login=$SONAR