language: java
addons:
  chrome: stable
jdk:
  - openjdk11
branches:
  only:
    - develop
    - /^release-[0-999].[0-999]$/
    - master
    - issue#77
notifications:
  email:
    recipients:
      - ilya.kab@gmail.es
services:
  - docker

before_install:
  - touch .env
  - docker-compose up -d

script:
  - mvn verify
  # test unitario  de integracion con cobertura
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=ruskab-github -Dsonar.login=$SONAR

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU
  app: agrim-manager
  on:
    repo: Ruskab/agrimManager
    branch: develop