version: '3'

services:
  mysql:
    container_name: mysql-db
    image: mysql:5.7.28
    ports:
      - "3360:3306"
    volumes:
      - mysql-db-data://var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  tomcat:
    container_name: tomcat9
    build: .
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: ${MYSQL_DATABASE}
    ports:
      - "8080:8080"
    links:
      - mysql

volumes:
  mysql-db-data:
