version: '3'

services:
  mysql:
    container_name: mysql-db
    image: mysql:5.7.28
    ports:
      - "127.0.0.1:33060:3306"
    volumes:
      - mysql-db-data://var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${AGRIM_DB_PASS}
      - MYSQL_DATABASE=${AGRIM_DB_NAME}
      - MYSQL_USER=${AGRIM_DB_USER}
      - MYSQL_PASSWORD=${AGRIM_DB_PASS}


  tomcat:
    container_name: tomcat9
    build: .
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${AGRIM_DB_PASS}
      - MYSQL_DATABASE=${AGRIM_DB_NAME}
      - MYSQL_HOST=mysql
      - MYSQL_USER=${AGRIM_DB_USER}
      - MYSQL_PASSWORD=${AGRIM_DB_PASS}
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - mysql

volumes:
  mysql-db-data: