version: '3'

services:
  mysql:
    container_name: mysql-db
    image: mysql:5.7.28
    ports:
      - "127.0.0.1:33060:3306"
    volumes:
      - mysql-db-data://var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${TRAVIS_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  tomcat:
    container_name: tomcat9
    build: .
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${TRAVIS_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=mysql
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - mysql

volumes:
  mysql-db-data: