version: '3'

services:

  mysql:
    container_name: mysql-db
    image: mysql:5.7.28
    environment:
      # So you don't have to use root, but you can if you like
      # MYSQL_USER: 'user'
      # You can use whatever password you like
      #MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: agrim_manager
    # <Port exposed> : < MySQL Port running inside container>
    ports:
      - "33060:3306"
    # Where our data will be persisted
    volumes:
      - mysql-db-data://var/lib/mysql
# Names our volume
volumes:
  mysql-db-data:
