version: '3'

services:

  mysql:
    container_name: mysql-db
    image: mysql:5.7.28
    # <Port exposed> : < MySQL Port running inside container>
    ports:
      - "33060:3306"
    # Where our data will be persisted
    volumes:
      - mysql-db-data://var/lib/mysql
    env_file:
      - .env
# Names our volume
volumes:
  mysql-db-data:
