@startuml


(*) --> "<img:../png/Agrim_login.png>" as INIT_LOGIN #LawnGreen

'INIT_LOGIN -right-> "<img:../png/Agrim_signin.png>" as INIT_SIGNIN


'INIT_SIGNIN --> OPENED_DASHBOARD #LawnGreen
'note on link
'sign in
'end note

INIT_LOGIN --> "<img:../png/Agrim_dashboard.png>" as OPENED_DASHBOARD #LawnGreen
note on link
login
end note

'OPENED_DASHBOARD --> "<img:../png/Agrim_newIntervention.png>" as CREATE_INTERVENTION
'note on link
'    createIntervention
'end note
'
'CREATE_INTERVENTION --> OPENED_DASHBOARD

OPENED_DASHBOARD -right-> "<img:../png/Agrim_clients.png>" as OPENED_CLIENTS #LawnGreen
note on link
    openClients
end note

'
'OPENED_CLIENTS --> "<img:../png/Agrim_configClient.png>" as CONFIG_CLIENT
'note on link
'configClient
'end note

'CONFIG_CLIENT --> OPENED_CLIENTS
'
OPENED_DASHBOARD --> "<img:../png/Agrim_Interventions.png>" as OPENED_INTERVENTIONS #LawnGreen
note on link
    openInterventions
end note
'
OPENED_DASHBOARD -left-> "<img:../png/Agrim_vehicles.png>" as OPENED_VEHICLES #LawnGreen
note on link
    openVehicles
end note

'OPENED_VEHICLES --> "<img:../png/Agrim_configVehicle.png>" as CONFIG_VEHICLE
'note on link
'configVehicle
'end note
'
'CONFIG_VEHICLE --> OPENED_VEHICLES

OPENED_DASHBOARD --> "<img:../png/Agrim_Operations.png>" as OPENED_OPERATIONS #LawnGreen

OPENED_DASHBOARD --> "<img:../png/Agrim_MyInterventions.png>" as OPENED_MY_INTERVENTIONS #LawnGreen

OPENED_CLIENTS --> OPENED_VEHICLES
OPENED_CLIENTS --> OPENED_INTERVENTIONS
OPENED_CLIENTS --> OPENED_DASHBOARD
OPENED_CLIENTS --> OPENED_MY_INTERVENTIONS
OPENED_CLIENTS --> OPENED_OPERATIONS

'

@enduml
