@startuml
!procedure _openedInterventions() #LawnGreen
{+
{* Dashboard | Clients | Vehicles | <b>Interventions | Username }

    {^"<i><color:blue>if exists Interventions"
        {#
            Start | End | Vehicles | Type
            03-07-2017 12:00:00 | 01-02-2017 14:20:00 | - | CAFE
            03-07-2017 12:00:00 | - | Mazda - CJO32NAH | REPAIR
        }
    }
}

!endprocedure

@enduml
