@startuml
!procedure _openedClient() #LawnGreen
{+

    {^"Client: Alexander"

        {^"<i><color:blue>if Contact opened"
            {/ <b>Contact | Vehicles | Billable | [x]}
            {
                Full name : | "Alexander Hamilton"
            }
            [Save]
        }

        {^"<i><color:blue>if vehicles opened"
            {/ Contact | <b>Vehicles | Billable | [x]}
            {
                {^"Vehicles"
                    {+
                        Registration plate | 32194744
                        Brand | Seat
                        Next ITV | 03-03-2017
                    }
                }
            }
            [Save]
        }

        {^"<i><color:blue>if Billable opened"

            {/ Contact | Vehicles | <b>Billable | [x]}
            {
                Pending to invoice : | "32" | [<&minus>] | [<&plus>]
            }
            [Save]
        }
        }
}
!endprocedure

@enduml
