@startuml

state 3 <<choice>>
state 9 as ":OPENED_VEHICLES"
state 1 as " "
state 2 as " "
state 3 as " "
state 4 as " "
state 6 as " "
state 7 as " "
state 8 as " "
state 10 as " "
state A1 as " "
state A0 as " "
state A2 as " "

[*] --> 1
note on link
    mechanic orders create vehicle
end note

1 --> 2
note on link
    <b>System allows</b>
    * input for
    ** vehicle registration plate
    ** brand
    ** client name
    ** client body of frame
    ** KMS
    * order skip to last step
    * order go to next step
    ** cancel
end note

2 --> 1
note on link
    * mechanic introduces
    ** vehicle registration plate
    ** vehicle brand
    ** vehicle client name
    ** vehicle client body of frame
    ** vehicle KMS
    ** project cost
    * mechanic orders go to last step
end note

2 --> 10
note on link
mechanic orders to cancel
end note

2 --> 3
note on link
 mechanic orders go to next step
end note

3 --> 1
note on link
    [empty registration plate OR brand OR client Name]
end note

3 --> 6
note on link
    [skip to last]
end note

3 --> 4

4 --> A0
note on link
    <b>System allows</b>
    * input
    **last ITV date
    **next ITV date
    * order go to next step
    * order go to previous step
    * cancel
end note

A0 --> 4
note on link
    Mechanic introduces
    * last ITV
    * next ITV
end note

A0 --> 10
note on link
mechanic orders to cancel
end note

A0 --> 1
note on link
mechanic orders go to previous step
end note

A0 --> A1
note on link
mechanic orders go to next step
end note

A1 --> A2
note on link
    <b>System allows</b>
    * input
    ** last revision date
    ** air filter reference
    ** oil filter reference
    ** fuel filter reference
    ** motor oil
    * order go to next step
    * order go to previous step
    * order to cancel
end note

A2 --> A0
note on link
    mechanic orders go to previous step
end note

A2 --> 10
note on link
    mechanic orders to cancel
end note

A2 --> 6
note on link
 mechanic orders go to next step
end note

6 --> 7
note on link
    <b>System shows</b>
    * All vehicle information to be created
    <b>System allows</b>
    * confirm vehicle creation
    * order to cancel
    * go to previous step
end note

7 --> A1
note on link
    Mechanic orders go to previous step
end note

7 --> 10
note on link
    mechanic orders to cancel
end note

10 --> 9
note on link
<b>System shows</b>
* message vehicle is created
* all vehicles
<b>System allows</b>
* order create vehicle
* order update vehicle
* order read vehicle
* order open dashboard
* order open interventions
* order open clients
* order open operations
* order logout
* order create intervention>
end note

7 --> 8
note on link
 Mechanic orders confirm vehicle creation
end note

8 --> 9
note on link
<b>System shows</b>
* message vehicle is created
* all vehicles
<b>System allows</b>
* order create vehicle
* order update vehicle
* order read vehicle
* order open dashboard
* order open interventions
* order open clients
* order open operations
* order logout
* order create intervention>
end note
@enduml
