@startuml

state 0 as ":OPENED_CLIENTS"
state 1 as "CONTACT_INFO_OPENED"
state B1 as "BILLING_INFO_OPENED"
state A2 as "VEHICLES_INFO_OPENED"
state 2 as " "
state A3 as " "
state B2 as " "

[*] --> 1
note on link
    mechanic introduces a client to open
end note

1 --> 2
note on link
<b>System shows</b>
* client contact information
** full Name
<b>System allows</b>
* introduce client full name
* go to client vehicles information
* go to client billable information
* save changes
* cancel
end note

2 --> 1
note on link
* Mechanic introduces client fullName
* Mechanic orders save chages
end note

2 --> 0
note on link
mechanic orders to cancel
end note

2 --> A2
note on link
Mechanic orders go to client vehicles information
end note

2 --> B1
note on link
Mechanic orders go to billable information
end note

B1 --> B2
note on link
    <b>System shows</b>
    * client pending hours to invoice
    <b>System allows</b>
    * introduce pending hours to invoice
    * go to client contact information
    * go to client vehicles information
    * save changes
    * cancel
end note

B2 --> B1
note on link
* Mechanic introduces client pending hours to invoice
* Mechanic orders save changes
end note

B2 --> A2
note on link
 Mechanic orders go to client vehicles information
end note

B2 --> 1
note on link
 Mechanic orders go to client contact information
end note

B2 --> 0
note on link
mechanic orders to cancel
end note

A2 --> A3
note on link
    <b>System shows</b>
    * client vehicles
    <b>System allows</b>
    * add vehicle
    * remove vehicle
    * go to contact information
    * save changes
    * cancel
end note

A3 --> A2
note on link
* Mechanic adds vehicle
* Mechanic removes vehicle
* Mechanic orders save changes
end note

A3 --> B1
note on link
Mechanic orders go to billable information
end note

A3 --> 1
note on link
Mechanic orders go to contact information
end note

A3 --> 0
note on link
Mechanic orders to cancel
end note

@enduml
