@startuml

state 1 <<choice>>
state 2 as " "
state 4 as " "

[*] --> 1
note on link
    mechanic orders open interventions
end note

1 --> 2
note on link
    [no interventions to show]
end note

1 --> 4

4 --> [*]
note on link
    * System shows
    ** all interventions
    * System allows
    ** order open dashboard
    ** order open clients
    ** order open vehicles
    ** order open operations
    ** order logout
    ** order create intervention
end note

2 --> [*]
note on link
    * System shows
    ** no interventions to show
    * System allows
    ** order open dashboard
    ** order open clients
    ** order open vehicles
    ** order open operations
    ** order logout
    ** order create intervention
end note

@enduml
