@startuml

state 1 <<choice>>
state 2 as " "
state 4 as " "

[*] --> 1
note on link
    mechanic orders open clients
end note

1 --> 2
note on link
    [no clients to show]
end note

1 --> 4

4 --> [*]
note on link
    * System shows
    ** all clients
    * System allows
    ** order create client
    ** order update client
    ** order read client
    ** order open dashboard
    ** order open interventions
    ** order open vehicles
    ** order open operations
    ** order logout
    ** order create intervention
end note

2 --> [*]
note on link
    * System shows
    ** no clients to show
    * System allows
    ** order create client
    ** order open dashboard
    ** order open interventions
    ** order open vehicles
    ** order open operations
    ** order logout
    ** order create intervention
end note

@enduml
