@startuml
!procedure _openedVehicles() #LawnGreen
{+
{* Dashboard | Clients | <b>Vehicles | Interventions | Username }

    {^"<i><color:blue>if exists vehicles"
        {#
            Registration plate | Brand | Client | body on Frame | Last Revision Date | Itv Date | Next Itv date
            HG7UNQKA | Mercedes-Benz | Ilya | VF1KC0JEF369332 | 03-03-2017 | 03-05-2017 | 01-02-2011
            NIY2E48J | Tata | Alexander | VF1KC0JEF369332 | 03-03-2017 | 03-07-2017 | 01-02-2012
        }
        [create]
    }
}
!endprocedure

@enduml
