@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view ClientsView
view ConfigClientView
controller ConfigClientController
model ClientsDao
model Client
model Vehicle
model VehiclesDao

user -right-> ClientsView
note on link
    configClient(clientId)
end note

user -right-> ConfigClientView
note on link
setFullName(fullName)
setBillableHours(billableHours)
save(client)
end note

ClientsView -down-> ConfigClientView
note on link
   new ConfigClientView(client)
end note

ConfigClientView -right-> ConfigClientController
note on link
    readVehicles(clientId)
    save(client)
end note


ConfigClientController --> ClientsDao
note on link
    save(client)
end note

ConfigClientController --> VehiclesDao
note on link
    readVehicles(clientId)
end note

ConfigClientView --> Client
ConfigClientView ----> Vehicle
ConfigClientController .. "1" Client
ConfigClientController .. "0..*" Vehicle
ClientsDao .. Client
VehiclesDao .. Vehicle
@enduml
