@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor actor
view ":MenuView" as MenuView
view ":InterventionCreateView" as InterventionCreateView
controller InterventionCreateController
model InterventionsDao
model Intervention
model VehiclesDao
model Vehicle
collaboration ":Collaboration OpenDashboard" as s1

actor -down-> MenuView
note on link
    createIntervention()
end note

actor -right-> InterventionCreateView
note on link
searchVehicle(text)
setType(type)
setDescription(description)
confirmCreation()
end note

MenuView -right-> InterventionCreateView
note on link
    openInterventionCreateDialog()
end note


InterventionCreateView -up-> s1
note on link
    openDashboard()
end note

InterventionCreateView -right-> InterventionCreateController
note on link
    readVehicles(text)
    createIntervention(intervention)
end note

InterventionCreateController --> InterventionsDao
note on link
    create(intervention)
end note

InterventionCreateController --> VehiclesDao
note on link
    searchVehicle(text)
end note


InterventionCreateView --> Intervention
VehiclesDao -- Vehicle
InterventionsDao .. Intervention
InterventionCreateController .. "1" Intervention
InterventionCreateController .. "*" Vehicle


@enduml