@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view ClientsView
view createClientView
controller CreateClientController
collaboration ":Collaboration OpenClients" as OpenClients
model ClientDao
model Client

user -right-> ClientsView
note on link
    createClient()
end note

user --> createClientView
note on link
    setFullName(fullName)
    setBillableHours(billableHours)
    confirmCreation()
end note

ClientsView -down-> createClientView
note on link
    new createClientView()
end note

createClientView -right-> CreateClientController
note on link
    createClient(client)
end note

createClientView --> "1" Client

createClientView --> OpenClients
note on link
openClients()
end note

CreateClientController -right-> ClientDao
note on link
    createClient(client)
end note

ClientDao .. Client

CreateClientController .right. "1" Client
@enduml