@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor actor
view ":MenuView" as MenuView
view CreateInterventionView
controller InterventionCreateController
controller OpenVehiclesController
model InterventionsDao
model Intervention
model VehiclesDao
model Vehicle
collaboration ":Collaboration OpenDashboard" as s1

actor -down-> MenuView
note on link
    createIntervention()
end note

actor -right-> CreateInterventionView
note on link
searchVehicles(text)
setType(type)
setDescription(description)
confirmCreation()
end note

MenuView -right-> CreateInterventionView
note on link
    new CreateInterventionView()
end note

CreateInterventionView -right-> "*" Vehicle

CreateInterventionView -up-> s1
note on link
    openDashboard()
end note

CreateInterventionView --> OpenVehiclesController
note on link
    searchVehicles(text)
end note

CreateInterventionView -right-> InterventionCreateController
note on link
    createIntervention(intervention)
end note

InterventionCreateController --> InterventionsDao
note on link
    create(intervention)
end note

OpenVehiclesController --> VehiclesDao
note on link
    searchVehicle(text)
end note


CreateInterventionView --> Intervention
VehiclesDao -- Vehicle
InterventionsDao .. Intervention
InterventionCreateController .. "1" Intervention
OpenVehiclesController .. "*" Vehicle


@enduml