@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view VehiclesView
view VehicleCreateView
controller CreateVehicleController
controller OpenClientsController
collaboration ":Collaboration OpenVehicles" as OpenVehicles
model VehicleDao
model ClientDao
model Vehicle
model Client

user -right-> VehiclesView
note on link
    createVehicle()
end note

user --> VehicleCreateView
note on link
setVehicle(data)
searchClient(text)
setClient(clientId)
confirmCreation()
end note

VehiclesView -down-> VehicleCreateView
note on link
    new VehicleCreateView()
end note

VehicleCreateView -right-> CreateVehicleController
note on link
    createVehicle(vehicle)
end note

VehicleCreateView -right-> OpenClientsController
note on link
    searchClients(query)
end note

VehicleCreateView --> OpenVehicles
note on link
openVehicles()
end note

VehicleCreateView --> "1" Vehicle
VehicleCreateView --> "*" Client

CreateVehicleController -right-> VehicleDao
note on link
    createVehicle(vehicle)
end note

OpenClientsController --> ClientDao
note on link
    searchCliensByName(query)
end note

VehicleDao .... Vehicle

ClientDao .. Client

CreateVehicleController .right. "1" Vehicle

OpenClientsController .. "*" Client
@enduml