@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor actor

view DashboardView

controller FinishInterventionController
collaboration ":Collaboration OpenDashBoard" as OpenDashBoard

model MechanicsDao
model Mechanic
model Intervention

actor --> DashboardView
note on link
    finishIntervention(interventionId)
end note

DashboardView -right-> FinishInterventionController
note on link
    finishIntervention(mechanicId, interventionId)
end note

DashboardView -- OpenDashBoard
note on link
    openDashboard()
end note

FinishInterventionController -down-> MechanicsDao
note on link
    read(mechanicId)
    update(mechanic)
end note

FinishInterventionController .down.> "1" Mechanic
note on link
    setEntTIme(interventionId, now())
end note

MechanicsDao -- Mechanic
Mechanic -right- Intervention

@enduml