@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view LoginView
controller LoginController
model MechanicsDao
model Mechanic
model Session
collaboration ":Collaboration OpenDashboard" as OpenDashboard


user -right-> LoginView
note on link
    login(username, password)
end note

LoginView -right-> LoginController
note on link
    login(username, password)
    searchBy(username, password)
end note

LoginView -up-> OpenDashboard
note on link
    openDashboard(session)
end note

LoginView ..> "1" Session
note on link
    setMechanic(mechanic)
end note

LoginController -down-> MechanicsDao
note on link
    serchBy(username, password)
end note

LoginView --> "1" Mechanic
LoginController .. Mechanic
MechanicsDao -- Mechanic

@enduml