@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view LoginView
controller LoginController
model MechanicDao
model Mechanic
model Session
collaboration ":Collaboration OpenDashboard" as OpenDashboard


user -right-> LoginView
note on link
    login(username, password)
end note

LoginView -right-> LoginController
note on link
    login(username, password)
    findBy(username, password)
end note

LoginView -up-> OpenDashboard
note on link
    openDashboard(session)
end note

LoginView --> Session
note on link
    setMechanic(mechanic)
end note

LoginController -down-> MechanicDao
note on link
    findBy(username, password)
end note

LoginView --> Mechanic
LoginController .. Mechanic
MechanicDao -- Mechanic

@enduml