@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user

view MenuView
view ClientsView

controller OpenClientsController

model ClientDao
model Client

user --> MenuView
note on link
    openClients()
end note

MenuView -right-> ClientsView
note on link
    new ClientsView()
end note

ClientsView -right-> OpenClientsController
note on link
    readAllClients()
end note

OpenClientsController --> ClientDao
note on link
0 : readAllClients()
end note

OpenClientsController .. "0..*" Client

ClientDao .. Client

ClientsView --> Client

@enduml