@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor actor

view MenuView
view DashboardView

controller openDashboardController

model InterventionDao
model VehicleDao
model Intervention
model Session
model Vehicle

actor --> MenuView
note on link
    openDashboard()
end note

MenuView -right-> DashboardView
note on link
    new DashboardView()
end note

DashboardView -down-> Session
note on link
    getMechanic()
end note
DashboardView -down-> Intervention
DashboardView -down-> Vehicle

DashboardView -right-> openDashboardController
note on link
    searchActiveInterventions(mechanic)
    searchVehicle(interventionId)
end note

openDashboardController -down-> InterventionDao
note on link
    searchActiveInterventions(mechanic)
end note

openDashboardController -right-> VehicleDao
note on link
    searchVehicle(interventionId)
end note

openDashboardController .. Vehicle
VehicleDao .down.. Vehicle
openDashboardController .down. "0..*" Intervention
InterventionDao -left- Intervention

@enduml