@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user

view MenuView
view VehiclesView

controller OpenVehiclesController

model VehiclesDao
model ClientsDao
model Vehicle
model Client

user --> MenuView
note on link
    openVehicles()
end note

MenuView -right-> VehiclesView
note on link
    new VehiclesView()
end note

VehiclesView -right-> OpenVehiclesController
note on link
    readAllVehicles()
    readClient(clientId())
end note

OpenVehiclesController --> VehiclesDao
note on link
readAllVehicles()
end note

OpenVehiclesController --> ClientsDao
note on link
readClient(clientId)
end note

OpenVehiclesController .. "0..*" Vehicle
OpenVehiclesController .. "1" Client
ClientsDao .. Client
VehiclesDao .. Vehicle
VehiclesView ----> Vehicle
VehiclesView --> Client
@enduml