@startuml

actor :User:
'boundary Boundary
'control Control
'entity Entity

boundary LoginView as b1
boundary DashboardView as b2

control LoginController as c1
control DashboardController as c2


entity Mechanics as e1
entity Mechanic as e2

User --> b1
b1 --> b2
b2 --> c2

b1 --> c1
c1 --> e1
c1 --> e2
e1 --> e2


@enduml