@startuml

actor :User:
'boundary Boundary
'control Control
'entity Entity

boundary ClientsView as b1
boundary DashboardView as b2
boundary VehiclesView as b4
boundary InterventionCreateView as b5
boundary InterventionCreateAddVehicleView as b6
boundary InterventionCreateConfirmView as b7

control InterventionCreateController as c1
control VehicleOpenController as c2

entity Intervention as e1
entity Vehicle as e2

User --> b1
User --> b2
User --> b4
b1 --> b5
b2 --> b5
b4 --> b5
b5 --> b6
b5 --> b7
b6 --> b7
b7 --> c1
b6 --> c2
b4 --> c2
c1 --> e1
c2 --> e2


@enduml