@startuml
skinparam {
    NoteBackgroundColor #whiteSmoke
}

state OPENED_VEHICLES as ":OPENED_VEHICLES"
state openVehicles as ":openVehicles"

[*] -down-> createVehicle

state createVehicle {
state 1 as " "
state A0 as " "
state A1 as " "
state 2 as " "
state 4 as " "
state A4 <<choice>>
state 6 as " "

[*]  -[#Green]down-> 1
note on link
    <b>Mechanic requests to</b>
    * create Vehicle
end note

1 -[#Green]down-> 2
note on link
    <b>System requires</b>
    * Registration plate (mandatory)
    * Brand (mandatory)
    * Client Name (mandatory)
    * Body of Frame
    * KMS
    <b>System allows</b>
    * cancel
    * skip optional information
end note

2 -down-> [*]
note on link
<b>mechanic requests to
* cancel
end note

2 -[#Green]down-> A4
note on link
<b>Mechanic provides</b>
* Registration plate (mandatory)
* Brand (mandatory)
* Client Name (mandatory)
end note

A4 -[#Green]down-> A1
note on link
[skip optional info]
end note


A4 -[#Green]down-> 4

4 -[#Green]down-> A0
note on link
<b>System requires</b>
* last ITV date
* next ITV date
<b>System allows</b>
* go back
* cancel
end note

A0 -left-> 1
note on link
<b>Mechanic requests to</b>
* go back
end note

A0 -down-> [*]
note on link
<b>Mechanic requests to</b>
* cancel
end note

A0 -[#Green]down-> A1
note on link
<b>User provides</b>
* last ITV date
* next ITV date
end note

A1 -[#Green]down-> 6
note on link
    <b>System shows</b>
    * new Vehicle
    ** Registration plate
    ** Brand
    ** Client Name
    ** Body of Frame
    ** KMS
    ** Last ITV date
    ** Next ITV date
    <b>System allows</b>
    *confirm creation
    *cancel
    *go back
end note

6 -[#Green]down-> [*]
note on link
<b>User requests to</b>
* confirm creation
end note

6 -up-> 4
note on link
<b>User requests to</b>
* go back
end note

6 -down-> [*]
note on link
<b>User requests to</b>
* cancel
end note
}

createVehicle --> openVehicles

openVehicles --> OPENED_VEHICLES
note on link
<b>System shows</b>
* all vehicles in system
<b>System allows</b>
* create client
* update vehicle
* read vehicle
* open dashboard
* open interventions
* open clients
* open operations
* logout
* create intervention
end note

@enduml
