@startuml
skinparam {
    NoteBackgroundColor #whiteSmoke
}


state initState as ":OPENED_DASHBOARD"
state initState2 as ":OPENED_VEHICLES"
state initState3 as ":OPENED_INTERVENTIONS"
state initState4 as ":OPENED_CLIENTS"
state OPENED_DASHBOARD as ":OPENED_DASHBOARD"
state openDashboard as ":openDashboard"

initState --> createIntervention
initState2 --> createIntervention
initState3 --> createIntervention
initState4 --> createIntervention

state createIntervention {
state 1 as " "
state 2 as " "
state 4 as " "
state 5 as " "
state 6 as " "
state 7 as " "

[*] -[#Green]-> 1
note on link
    <b>mechanic requests to</b>
    * create new intervention
end note

1 -[#Green]-> 2
note on link
<b>System requires</b>
* vehicle
** (should exist in the system)
** (mandatory when type REPAIR)
* intervention type
** REPAIR | CAFE
<b>System allows</b>
* cancel
end note

2 --> [*]
note on link
<b>Mechanic requests to</b>
* cancel
end note

2 -[#Green]-> 4
note on link
<b>Mechanic provides</b>
* vehicle
* intervention type
end note

4 -[#Green]-> 5
note on link
<b>System requires</b>
* intervention description
<b>System allows</b>
* cancel
* go to previous step
end note

5 --> 1
note on link
<b>Mechanic requests to</b>
* go to previus step
end note

5 -[#Green]-> 6
note on link
<b>Mechanic provides</b>
* intervention description
end note

6 -[#Green]-> 7
note on link
<b>System shows</b>
* description
* type
<b>System allows</b>
* go to previous step
* cancel
* confirm creation
end note

7 --> [*]
note on link
<b>Mechanic requests to</b>
* cancel
end note

7 --> 4
note on link
<b>Mechanic requests to</b>
* previous step
end note

7 -[#Green]-> [*]
note on link
<b>mechanic requests to
* confirm creation
end note

}

createIntervention --> openDashboard

openDashboard --> OPENED_DASHBOARD
note on link
    <b>System shows</b>
    * created intervention
    **Type
    **Start datetime
    <b>System allows</b>
    *  open vehicles
    *  open interventions
    *  open clients
    *  open operations
    *  logout
    *  create intervention
    *  finish intervention
end note
@enduml
