@startuml

state 2 as " "

[*] --> 2
note on link
    mechanic orders finish intervention
end note

2 --> [*]
note on link
    * System shows
    ** mechanic active interventions
    * System allows
    ** order open vehicles
    ** order open interventions
    ** order open clients
    ** order open operations
    ** order logout
    ** order create intervention
    ** order finish intervention
end note

@enduml
