@startuml
skinparam {
    NoteBackgroundColor #whiteSmoke
}

state openDashboard as ":openDashboard"
state OPENED_DASHBOARD as ":OPENED_DASHBOARD"

[*] --> finishIntervention
note on link
    <b>mechanic requests to</b>
     finish intervention
end note

state finishIntervention{
    [*] --> [*]
}

finishIntervention --> openDashboard

openDashboard --> OPENED_DASHBOARD
note on link
<b>System shows</b>
    * mechanic active interventions
<b>System allows</b>
    * order open vehicles
    * order open interventions
    * order open clients
    * order open operations
    * order logout
    * order create intervention
    * order finish intervention
end note

@enduml
