@startuml
    skinparam {
        NoteBackgroundColor #whiteSmoke
    }

state initstate as "INIT"
state login
state openDashboard as ":openDashboard"
state endstate as ":OPENED_DASHBOARD"

initstate --> login

state login {

state 1 as " " #LawnGreen
state condicional <<choice>>
state 2 as " " #LawnGreen
state 3 as " " #LawnGreen

[*] --> 1
note on link
<b>User requests to</b>
* login
end note

1 --> 2
note on link
<b>System requires</b>
* username
* password
end note

2 --> condicional
note on link
<b>User provides</b>
* username
* password
end note

condicional --> 1
note on link
[pair username password not exists]
end note

condicional --> 3

3 --> [*]
note on link
<b>System shows</b>
* Login successful
end note


}

login --> openDashboard

openDashboard --> endstate
note on link
<b>System shows</b>
* mechanic avtive interventions [mechanic has active interventions]
<b>System allows</b>
* open vehicles
* open interventions
* open clients
* open operations
* create intervention
* finish intervention [mechanic has active interventions]
* logout
end note

@enduml