@startuml
    skinparam {
        NoteBackgroundColor #whiteSmoke
    }

state initstate as "INIT"
state usecase as "login"
state endstate as ":OPENED_DASHBOARD"

initstate --> usecase

state usecase {

state 1 as " " #LawnGreen
state condicional <<choice>>
state 2 as " " #LawnGreen
state 3 as " " #LawnGreen
state 4 as " "

[*] --> 1
note on link
User requests to login
end note

1 --> 2
note on link
<b>System requires</b>
* username
* password
<b>System allows</b>
* cancel
end note

2 --> 4
note on link
User requests to cancel
end note

2 --> condicional
note on link
User provides
* username
* password
end note

condicional --> 1
note on link
[pair username password not exists]
end note

condicional --> 3

3 --> [*]
note on link
<b>System shows</b>
* Login successful
end note

4 --> [*]
note on link
<b>System shows</b>
* Operation cancelled
end note

}

usecase --> endstate
note on link
<b>System shows</b>
* [mechanic has active interventions] mechanic avtive interventions
<b>System allows</b>
* order open vehicles
* order open interventions
* order open clients
* order open operations
* order create intervention
* order finish intervention
* order logout
end note

@enduml