@startuml

skinparam {
    NoteBackgroundColor #whiteSmoke
}

state initial as ":INITIAL"

[*] --> logout
note on link
<b>mechanic request to</b>
* logout
end note

state logout {

[*] --> [*]

}
logout --> initial
note on link
    <b>System allows</b>
    * login
    * sign in
end note



@enduml
