@startuml

state 1 <<choice>>
state 2 as " "
state 4 as " "

[*] --> 1
note on link
    mechanic orders open vehicles
end note

1 --> 2
note on link
    [no vehicles to show]
end note

1 --> 4

4 --> [*]
note on link
    * System shows
    ** all vehicles
    * System allows
    ** order create vehicle
    ** order update vehicle
    ** order read vehicle
    ** order open dashboard
    ** order open interventions
    ** order open clients
    ** order open operations
    ** order logout
    ** order create intervention
end note

2 --> [*]
note on link
    * System shows
    ** no vehicles to show
    * System allows
    ** order create vehicle
    ** order open dashboard
    ** order open interventions
    ** order open clients
    ** order open operations
    ** order logout
    ** order create intervention
end note

@enduml
