@startuml
skinparam {
        NoteBackgroundColor #whiteSmoke
}

[*] --> openDashboard
note on link
<b>User requests to</b>
* openDashboard
end note

state openDashboard {

[*] --> [*]


}

openDashboard --> [*]
note on link
<b>System shows
* mechanic active interventions
<b>System allows
* open vehicles
* open interventions
* open clients
* open operations
* logout
* create intervention
* finish intervention
end note

@enduml
