@startuml
skinparam {
        NoteBackgroundColor #whiteSmoke
}

[*] --> openInterventions
note on link
<b>User requests to</b>
* openInterventions
end note

state openInterventions {
    [*] --> [*]
}

openInterventions --> [*]
note on link
<b>System shows
* all interventions
<b>System allows
* open dashboard
* open clients
* open vehicles
* open operations
* logout
* create intervention
end note

@enduml
