@startuml

@startuml
    skinparam {
        NoteBackgroundColor #whiteSmoke
    }

state initstate as "OPEN_VEHICLES"
state usecase as "openVehicle"
state endstate as "OPEN_VEHICLE"

initstate --> usecase
note on link
<b>User requests to</b>
* openVehicle
end note

state usecase {
    [*] --> [*]
}

usecase --> endstate
note on link
<b>System shows</b>
* vehicle
** ...info
<b>System allows</b>
* update vehicle
* open vehicles
end note

@enduml
