@startuml

@startuml
    skinparam {
        NoteBackgroundColor #whiteSmoke
    }

state initstate as ":OPEN_VEHICLE"
state usecase as "openVehicle"
state endstate as ":OPEN_VEHICLE"
state endstateCancel as ":OPEN_VEHICLES"

initstate -[#Green]-> usecase

state usecase {
    [*] -[#Green]-> 1
    note on link
    <b>User requests to</b>
    * updateVehicle
    end note
    
    1 -[#Green]-> 2
    note on link
    <b>System shows</b>
    * Vehicle information
    ** Registration plate
    ** Brand
    ** Client Name
    ** Body of Frame
    ** KMS
    ** Last ITV
    ** Next ITV
    ** Last Revision
    ** Air Filter Reference
    ** Oil Filter Reference
    ** Fuel Filter
    ** Motor Oil
    <b>System allows</b>
    * Modify full Name
    * Confirm update
    * Cancel update
    end note

    2 -[#Green]-> 1
    note on link
    <b>User provides</b>
    * Vehicle information
    end note

    2 --> endstateCancel
    note on link
    <b>User requests to</b>
    * cancel update
    end note

    2 -[#Green]-> 3
    note on link
    <b>User requests to</b>
    * confirm
    end note

    3 -[#Green]-> 4
    note on link
    <b>System shows</b>
    * information updated
    end note
}

4 -[#Green]-> endstate
note on link
<b>System shows</b>
* Vehicle
** full Name
** billable pending hours
<b>System allows</b>
* update client
* open clients
end note

endstate --> [*]
endstateCancel --> [*]


@enduml
