@startuml
object AutomobileRepairShop
object Mechanic {
    name
    rol
}
object Intervention {
    description
    starHour
    endHour
}
object Client {
    name
    surname

}
object Vehicle {
    registrationPlate
    lastITV : date
    nextITV : date

}
object RepairingPack {
    invoiceDate
    invoicedHours
}


AutomobileRepairShop *-- "*" Mechanic
AutomobileRepairShop *-- "*" Client
Mechanic *-- "*" Intervention
Mechanic ..> Vehicle
Mechanic ..> RepairingPack
Mechanic ..> Client
Client "1" *-down- Vehicle
RepairingPack "0..1" o-- "*" Intervention
Intervention o-- "0..1" Vehicle
@enduml
