@startuml
scale 350 width
[*] --> ACTIVE_INTERVENTION
ACTIVE_INTERVENTION --> PAUSED_INTERVENTION
PAUSED_INTERVENTION --> ACTIVE_INTERVENTION
ACTIVE_INTERVENTION --> ENDED_INTERVENTION
ENDED_INTERVENTION --> BILLED_INTERVENTION
@enduml