@startuml
left to right direction

package MechanicManagement {
:mechanic: --> (createMechanic)
:mechanic: --> (openMechanic)
:mechanic: --> (deleteMechanic)
:mechanic: --> (openMechanics)
:mechanic: --> (login)
:mechanic: --> (signUp)
:mechanic: --> (logout)
}

@enduml
