@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor :User: as actor
view LoginView as b1
controller LoginController as c1
model MechanicsEntity as e1
model MechanicEntity as e2
model SessionEntity as e3

actor --> b1

b1 --> c1
c1 --> e1
c1 --> e2
c1 --> e3

e1 --> e2
e3 --> e2


@enduml