@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor :User: as actor
view "ClientView" as b2
controller "UpdateClientController" as c1
model "ClientsEntity" as e1

actor --> b2
b2 --> c1
c1 --> e1
@enduml