@startuml
	class OpenInterventionsController {
	+readMechanics()
	+readInterventions(mechanicId)
	+readVehicle(vehicleId)
	}

	OpenInterventionsController --> VehiclesDao
	OpenInterventionsController --> InterventionsDao
	OpenInterventionsController --> MechanicsDao
	InterventionsView --> OpenInterventionsController
@enduml