@startuml
	class OpenDashboardController {
	+searchVehicle(vehicleId)
	+searchActiveInterventions(mechanicId)
	}

	DashboardView --> OpenDashboardController
	OpenDashboardController --> VehiclesDao
	OpenDashboardController --> InterventionsDao
@enduml