@startuml
	class LoginView {
	+signin(username, password, repeatPassword)
	+login(username, password)
	}

	LoginView --> LoginController
	LoginView ..> "1" Session
	LoginView --> "1" Mechanic
	LoginView --> SignInView
	LoginView --> OpenDashboard
@enduml