@startuml

left to right direction

package ClientsManagement {
:mechanic: --> (createClient)
:mechanic: --> (readClient)
:mechanic: --> (updateClient)
:mechanic: --> (deleteClient)
:mechanic: --> (addVehicle)
:mechanic: --> (removeVehicle)
:mechanic: --> (openClients)
}

@enduml
