@startuml
left to right direction


package InterventionsManagement {
:mechanic: --> (createIntervention)
:mechanic: --> (readIntervention)
:mechanic: --> (updateIntervention)
:mechanic: --> (openInterventions)
}
@enduml
