@startuml
left to right direction
!include actors.puml


package InterventionsManagement {
:mechanic: --> (createIntervention)
:mechanic: --> (readIntervention)
:mechanic: --> (updateIntervention)
:mechanic: --> (openInterventions)
}
@enduml
