@startuml

left to right direction


package VehiclesManagement {
:mechanic: --> (createVehicle)
:mechanic: --> (openVehicle)
:mechanic: --> (deleteVehicle)
:mechanic: --> (importVehicles)
:mechanic: --> (openVehicles)
}

@enduml
