@startuml
skinparam linetype polyline



package api as "API REST (Backend)" {

package  business_layer as "Business layer" #e1eced  {
    package api_controllers
    package business_controllers
    package business_services
    package exceptions

}

package data_layer as "Data layer" #e1eced {
    package data_services
    package daos
    package entities
}



package dto_layer as "data transfer layer" #e1eced {
    package dtos
}




}

package database_layer as "database layer" #e1eced {
database database
}

business_layer .[hidden].> dto_layer
data_layer .[hidden].> dto_layer
business_layer .[hidden]down...> data_layer


api_controllers ..> business_controllers
business_controllers ..> business_services
business_controllers ..> daos
business_controllers ....> data_services
data_services ..> daos
daos ..> entities

api_controllers ..> dtos
business_controllers ..> dtos
data_services ..> dtos
daos ..> dtos
dtos ..> entities
daos .down.> database
api_controllers .left.> exceptions
business_controllers .left.> exceptions

@enduml
