@startuml

!include configuration/StateDiagramsSetUp.puml



state initState as "OPENED_DASHBOARD"
state initState2 as "OPENED_VEHICLES"
state initState3 as "OPENED_INTERVENTIONS"
state initState4 as "OPENED_CLIENTS"
state initState5 as "OPENED_OPERATIONS"
state OPENED_DASHBOARD as "OPENED_DASHBOARD"
state openDashboard as ":openDashboard"

initState --> createIntervention
note on link
    <b>User requests to</b>
    * create new intervention
end note
initState2 --> createIntervention
note on link
    <b>User requests to</b>
    * create new intervention
end note
initState3 --> createIntervention
note on link
    <b>User requests to</b>
    * create new intervention
end note
initState4 --> createIntervention
note on link
    <b>User requests to</b>
    * create new intervention
end note
initState5 --> createIntervention
note on link
    <b>User requests to</b>
    * create new intervention
end note

state createIntervention {
state 1 as " "
state 2 as " "
state 3 as " "
state 4 as " "
state 5 as " "
state 9 as " "

[*] --> 1

1 --> 2
note on link
<b>System requires</b>
* vehicle
** (should exist in the system)
** (mandatory when type REPAIR)
* intervention type
* intervention description
** REPAIR | CAFE
<b>System allows</b>
* provide text for search vehicle datasheet
* cancel
end note

2 --> 3
note on link
<b>User provides</b>
* text for search vehicle datasheet
end note

3 --> 5
note on link
<b>System shows</b>
* vehicle datasheets that match the criteria 
<b>System allows</b>
* provide vehicle datasheet
* cancel
end note

5 -[#red]-> [*]
note on link
<b>User requests to</b>
* cancel
end note

5 --> 1
note on link
<b>User provides</b>
* vehicle datasheet
end note


2 -[#red]-> [*]
note on link
<b>Mechanic requests to</b>
* cancel
end note

2 --> 4
note on link
<b>Mechanic provides</b>
* vehicle
* intervention type
* intervention description
end note

4 --> 9
note on link
<b>System shows
* intervention type
* intervention description
* vehicle datasheet
<b>System allows
* confirm creation
* cancel
end note


9 -down[#red]-> [*]
note on link
<b> User requests to
* cancel
end note

9 -down---> [*]
note on link
<b>User requests to
* confirm creation
end note
}

createIntervention -[#red]-> OPENED_DASHBOARD

createIntervention --> openDashboard

openDashboard --> OPENED_DASHBOARD
@enduml
