@startuml
!include configuration/StateDiagramsSetUp.puml

state OPENED_VEHICLES as "OPENED_VEHICLES"
state openVehicles as ":openVehicles"
state initState as "OPENED_VEHICLES"

initState -down-> createVehicle
note on link
    <b>User requests to</b>
    * create Vehicle
end note

state createVehicle {
state 1 as " "
state 2 as " "

[*]  -down-> 1


1 -down-> 2
note on link
    <b>System requires</b>
    * vehicle information
    ** Registration plate (mandatory)
    ** Brand (mandatory)
    ** Client Name (mandatory)
    ** Body of Frame
    ** KMS
    <b>System allows</b>
    * cancel
end note

2 -down[#red]-> [*]
note on link
    <b>mechanic requests to
    * cancel
end note

2 -down-> [*]
note on link
<b>User provides</b>
* vehicle information
end note

createVehicle --> openVehicles

createVehicle -[#red]-> OPENED_VEHICLES

openVehicles --> OPENED_VEHICLES

@enduml
