@startuml

!include configuration/StateDiagramsSetUp.puml

state initState as "OPENED_CLIENTS"
state OPENED_CLIENTS as "OPENED_CLIENTS"
state openClients as ":openClients"

initState --> createClient
note on link
    <b>User requests to</b>
    * create Client
end note

state createClient {
state 1 as " "
state 2 as " "
state 6 as " "

[*]  -down-> 1

1 -down-> 2
note on link
    <b>System requires</b>
    * full Name (mandatory)
    * Billable hours
    <b>System allows</b>
    * confirm
    * cancel
end note

2 -down[#red]-> [*]
note on link
<b>User requests to
* cancel
end note

2 -down-> 6
note on link
<b>User provides</b>
* Full name
* pending billable hours
end note

6 -down-> [*]
note on link
<b>User requests to</b>
* confirm creation
end note

}

createClient -down-> openClients
createClient -[#red]-> OPENED_CLIENTS

openClients -down-> OPENED_CLIENTS


@enduml
