@startuml
skinparam {
    NoteBackgroundColor #whiteSmoke
}

state initState as ":OPENED_DASHBOARD"
state openDashboard as ":openDashboard"
state OPENED_DASHBOARD as ":OPENED_DASHBOARD"

initState --> finishIntervention
note on link
    <b>mechanic requests to</b>
     finish intervention
end note

state finishIntervention{
    [*] --> [*]
}

finishIntervention --> openDashboard

openDashboard --> OPENED_DASHBOARD
note on link
<b>System shows</b>
* mechanic active interventions
<b>System allows</b>
* open vehicles
* open interventions
* open clients
* open operations
* logout
* create intervention
* finish intervention
end note

@enduml
