@startuml

!include configuration/StateDiagramsSetUp.puml

state initState as "OPENED_DASHBOARD"
state openDashboard as ":openDashboard"
state OPENED_DASHBOARD as "OPENED_DASHBOARD"

initState --> finishIntervention
note on link
<b>User requests to</b>
* finish intervention
end note

state finishIntervention {
    [*] --> [*]
}

finishIntervention --> openDashboard

openDashboard --> OPENED_DASHBOARD
@enduml
