@startuml
!include configuration/StateDiagramsSetUp.puml

state initstate as "INITIAL"
state login
state openDashboard as ":openDashboard"
state endstate as ":OPENED_DASHBOARD"

initstate --> login
note on link
<b>User requests to</b>
* login
end note

state login {

state 1 as " "
state condicional <<choice>>
state 2 as " "

[*] --> 1

1 --> 2
note on link
<b>System requires</b>
* username
* password
end note

2 --> condicional
note on link
<b>User provides</b>
* username
* password
end note

condicional -[#red]-> 1
note on link
[pair username password not exists]
end note

condicional --> [*]
}

login --> openDashboard

openDashboard --> endstate

@enduml