@startuml

!include configuration/StateDiagramsSetUp.puml

state startState1 as "OPENED_VEHICLES"
state startState2 as "OPENED_CLIENTS"
state startState3 as "OPENED_INTERVENTIONS"
state startState4 as "INITIAL"
state startState5 as "OPENED_DASHBOARD"
state endState as "OPENED_DASHBOARD"

startState1 --> openDashboard
note on link
<b>User requests to</b>
* openDashboard
end note
startState2 --> openDashboard
note on link
<b>User requests to</b>
* openDashboard
end note
startState3 --> openDashboard
note on link
<b>User requests to</b>
* openDashboard
end note
startState4 --> openDashboard

startState5 --> openDashboard

state openDashboard {

[*] --> [*]
note on link
<b>System shows
* mechanic active interventions
<b>System allows
* open vehicles
* open interventions
* open clients
* open operations
* logout
* create intervention
* finish intervention
end note

}

openDashboard --> endState


@enduml
