@startuml
!include configuration/StateDiagramsSetUp.puml

state startState as "OPENED_OPERATIONS"
state endState as "OPENED_VEHICLE"

state startState1 as "OPENED_OPERATIONS"
state startState2 as "OPENED_CLIENTS"
state startState3 as "OPENED_INTERVENTIONS"
state startState5 as "OPENED_VEHICLE"
state endState as "OPENED_DASHBOARD"

startState1 --> openVehicles
note on link
<b>User requests to</b>
* openVehicles
end note
startState2 --> openVehicles
note on link
<b>User requests to</b>
* openVehicles
end note
startState3 --> openVehicles
note on link
<b>User requests to</b>
* openVehicles
end note
startState5 --> openVehicles
note on link
<b>User requests to</b>
* openVehicles
end note
startState --> openVehicles

state openVehicles {

[*] --> [*]


}

openVehicles --> endState
note on link
<b>System allows
* create Mechanic
* delete Mechanic
* import Vehicles
* open vehicles
* open clients
* open interventions
* open my interventions
* create intervention
* logout
end note

@enduml
