@startuml

!include configuration/StateDiagramsSetUp.puml

state startState as "OPENED_CLIENTS"
state startState2 as "OPENED_CLIENTS"
state startState3 as "OPENED_VEHICLES"
state startState4 as "OPENED_INTERVENTIONS"
state startState5 as "OPENED_OPERATIONS"
state endState as "OPENED_CLIENTS"

startState2 --> openClients

startState --> openClients
note on link
<b>User requests to</b>
* openClients
end note

startState3 --> openClients
note on link
<b>User requests to</b>
* openClients
end note

startState4 --> openClients
note on link
<b>User requests to</b>
* openClients
end note

startState5 --> openClients
note on link
<b>User requests to</b>
* openClients
end note

state openClients {
[*] --> [*]
note on link
<b>System shows
* all clients in system
<b>System allows
* open vehicles
* open interventions
* open clients
* open operations
* logout
* create intervention
* finish intervention
end note
}

openClients --> endState

@enduml
