@startuml

left to right direction

package ClientsManagement {
:mechanic: --|> :user:
:boss: --|> :user:
:developer: --|> :user:

:user: --> (createClient)
(createClient) ..> (openClients) : <<include>>
:user: --> (configClient)
(configClient) ..> (openClients) : <<include>>
:user: --> (deleteClient)
(deleteClient) ..> (openClients) : <<include>>
:user: --> (openClients)
}

@enduml
