@startuml

left to right direction

package ClientsManagement {
:mechanic: --|> :all:
:admin: --|> :all:
:developer: --|> :all:

:all: --> (createClient)
(createClient) ..> (openClients) : <<include>>
:all: --> (configClient)
(configClient) ..> (openClients) : <<include>>
:all: --> (deleteClient)
(deleteClient) ..> (openClients) : <<include>>
:all: --> (openClients)
}

@enduml
