@startuml
left to right direction


package InterventionsManagement {
:mechanic: --|> :user:
:developer: --|> :user:

:user: --> (createIntervention)
(createIntervention) ..> (openDashboard) : <<include>>
:admin: --> (openInterventions)
:developer: --> (openInterventions)
:user: --> (openMyInterventions)
}
@enduml
