@startuml
left to right direction

package MechanicManagement {
:mechanic: --|> :user:
:boss: --|> :user:
:developer: --|> :user:

:boss: --|> :administrator:
:developer: --|> :administrator:


:administrator: --> (createMechanic)
:user: --> (configMechanic)
:administrator: --> (deleteMechanic)
:administrator: --> (openMechanics)
:administrator: --> (openOperations)
:user: --> (login)
(login) ..> (openDashboard) : <<include>>
(signUp) ..> (openDashboard) : <<include>>
(configMechanic) ..> (openMechanics) : <<include>>
(createMechanic) ..> (openMechanics) : <<include>>
(deleteMechanic) ..> (openMechanics) : <<include>>
:user: --> (signUp)
:user: --> (logout)
}

@enduml
