@startuml

left to right direction


package VehiclesManagement {
:mechanic: --|> :all:
:admin: --|> :all:
:developer: --|> :all:

:admin: --|> :superUser:
:developer: --|> :superUser:

:all: --> (createVehicle)
(createVehicle) ..> (openVehicles) :<<include>>
:all: --> (configVehicle)
(configVehicle) ..> (openVehicles) : <<include>>
:superUser: --> (deleteVehicle)
(deleteVehicle) ..> (openVehicles) : <<include>>
:superUser: --> (importVehicles)
:all: --> (openVehicles)
(importVehicles) ..> (openVehicles) : <<include>>

}

@enduml
