@startuml

left to right direction


package VehiclesManagement {
:mechanic: --|> :user:
:boss: --|> :user:
:developer: --|> :user:

:boss: --|> :administrator:
:developer: --|> :administrator:

:user: --> (createVehicle)
(createVehicle) ..> (openVehicles) :<<include>>
:user: --> (configVehicle)
(configVehicle) ..> (openVehicles) : <<include>>
:administrator: --> (deleteVehicle)
(deleteVehicle) ..> (openVehicles) : <<include>>
:administrator: --> (importVehicles)
:user: --> (openVehicles)
(importVehicles) ..> (openVehicles) : <<include>>

}

@enduml
