@startuml
!procedure _openedDashboard()
{+
{* Dashboard | Clients | Vehicles | Interventions | Username
Interventions | New Intervention }

    {^"<i><color:blue>if active intervention"
        {^"<vehicle identification>"
          Type    | REPAIR
          Start date | 2020-09-19 12:00
          [  Finish   ]
        }
    }
}
!endprocedure

@enduml
