1@startuml

!include skinParams.puml

package Views {
    boundary DashboardView
    boundary OperationsView
    boundary CreateVehicleView
    boundary CreateClientView
    boundary ConfigClientView
    boundary ConfigVehicleView
    boundary VehiclesView
    boundary CreateInterventionView
    boundary MenuView
    boundary ConfigInterventionView
    boundary InterventionsView
    boundary MyInterventionsView
    boundary ClientsView
    boundary loginView
    boundary signInView
}

package Controllers {
    control openClientsController
    control openVehiclesController
    control openDashboardController
    control openOperations
    control openInterventionsController
    control openMyInterventionsController
    control createClientController
    control createVehicleController
    control createInterventionController
    control configClientController
    control configVehicleController
    control finishInterventionController
    control loginController
    control logoutController
    control signInController
}

package Models {
    entity Client
    entity Vehicle
    entity Intervention
    entity Mechanic
    entity RepairingPack
}

Views -[hidden]-- Controllers
Controllers -[hidden]- Models

'views
VehiclesView o-- CreateVehicleView
VehiclesView o-- ConfigVehicleView
ClientsView o-- ConfigClientView
ClientsView o-- CreateClientView
MenuView o-- CreateInterventionView
loginView o-- signInView
MyInterventionsView o-- ConfigInterventionView
InterventionsView o-- ConfigInterventionView

Client *-- Vehicle
Intervention o-- Vehicle
Mechanic *-- Intervention
RepairingPack o-- Intervention
@enduml