@startuml

!include skinParams.puml

package Views {
    boundary CreateVehicleView
    boundary CreateClientView
    boundary VehiclesView
    boundary ClientsView
    boundary CreateInterventionView
    boundary MenuView

    boundary VehicleView
    boundary MechanicView
    boundary AdminView
    boundary DeveloperView
    boundary InterventionView
    boundary RepairingPackView
    boundary loginView
    boundary signInView
}

package Controllers {
    control openClientsController
    control openVehiclesController
    control createClientController
    control createVehicleController
    control createInterventionController

    control openClientController
    control updateClientsController
    control openVehicleController
    control updateVehicleController
    control finishInterventionController
    control openInterventionsController
    control loginController
    control logoutController
    control signInController
    control openDashboardController
}

package Models {
    entity Client
    entity Vehicle
    entity Intervention
    entity RepairingPack
    entity Mechanic
}
@enduml