@startuml

!include skinParams.puml

package Views {
    boundary MechanicView
    boundary AdminView
    boundary DeveloperView

    boundary ClientView
    boundary VehicleView
    boundary InterventionView
    boundary RepairingPackView
    boundary MenuView

    boundary loginView
    boundary signInView
}

package Controllers {
    control createClientController
    control openClientController
    control openClientsController
    control updateClientsController
    control createVehicleController
    control openVehicleController
    control updateVehicleController
    control openVehiclesController
    control createInterventionController
    control finishInterventionController
    control openInterventionsController
    control loginController
    control logoutController
    control signInController
    control openDashboardController
}

package Models {
    entity ClientEntity
    entity VehicleEntity
    entity InterventionEntity
    entity RepairingPackEntity
    entity MechanicEntity
}
@enduml