name: docker compose github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AGRIM_DB_USER: ${{ secrets.AGRIM_DB_USER }}
      AGRIM_DB_PASS: ${{ secrets.AGRIM_DB_PASS }}
      AGRIM_DB_NAME: ${{ secrets.AGRIM_DB_NAME }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/checkout@v1
      - name: Build the docker-compose
        run: docker-compose -f docker-compose-github.yml up -d

      - name: Sleep 60 s
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - name: Check running containers
        run: docker ps

      - name: execute Unit and bussiness controller test + create database
        run: mvn test -Denvironment=githubdocker


      - name: execute API tests
        run: mvn verify -Denvironment=githubendtoend
