name: API contoller tests in deployed application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AGRIM_DB_USER: ${{ secrets.AGRIM_DB_USER }}
      AGRIM_DB_PASS: ${{ secrets.AGRIM_DB_PASS }}
      AGRIM_DB_NAME: ${{ secrets.AGRIM_DB_NAME }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/checkout@v1
      - name: Build the docker-compose
        run: docker-compose -f docker-compose-github.yml up -d

      - name: Sleep 30s
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - name: Check docker running containers
        run: docker ps

      - name: Unit and Bussiness controllers tests + create database
        run: mvn test -Denvironment=githubdocker


      - name: API tests
        run: mvn test -Denvironment=githubendtoend -Dtest=api.api_controllers.*IT
