name: API contoller aceptance tests in deployed application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AGRIM_DB_USER: ${{ secrets.AGRIM_DB_USER }}
      AGRIM_DB_PASS: ${{ secrets.AGRIM_DB_PASS }}
      AGRIM_DB_NAME: ${{ secrets.AGRIM_DB_NAME }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.9
        uses: actions/setup-java@v1
        with:
          java-version: 1.9

      - uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: create Mysql DB and deploy Tomcat 9 with the app
        run: docker-compose -f docker-compose-github.yml up -d

      - name: Wait for the environment in docker to get up
        run: |
          while ! docker exec mysql-db mysqladmin --user=${{ secrets.AGRIM_DB_USER }} --password=${{ secrets.AGRIM_DB_PASS }} --host "127.0.0.1" ping --silent &> /dev/null ; do
              echo "Waiting for database connection..."
              sleep 2
          done

      - name: Check docker running containers
        run: docker ps

      - name: Unit and Bussiness controllers tests
        run: mvn test -Denvironment=githubdocker


      - name: API tests
        run: mvn clean test -Denvironment=githubendtoend -Dtest=api.api_controllers.*IT
