name: maven unit test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: creare database mysql
        run: mysql -uroot -proot -e "CREATE DATABASE ${{ secrets.AGRIM_DB_NAME }};"

      - name: creare user mysql
        run: mysql -uroot -proot -e "create user ${{ secrets.AGRIM_DB_USER }}@localhost identified by '${{ secrets.AGRIM_DB_PASS }}'; "

      - name: show databases
        run: mysql -uroot -proot -e "show databases;"

      - name: grant privilegies to user
        run: mysql -uroot -proot -e "grant all privileges on agrim_manager.* to ${{ secrets.AGRIM_DB_USER }}@localhost;" agrim_manager 

      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit tests + Integration Tests
        run: mvn test -Denvironment=github -Dtest=api.business_controllers.*IT
        env:
          AGRIM_DB_USER: ${{ secrets.AGRIM_DB_USER }}
          AGRIM_DB_PASS: ${{ secrets.AGRIM_DB_PASS }}
